# SPDX-License-Identifier: GPL-2.0
# Kernel Makefile for Subleq

obj-y += head.o
obj-y += entry.o
obj-y += setup.o
obj-y += irq.o
obj-y += time.o
obj-y += process.o
obj-y += signal.o
obj-y += traps.o
obj-y += ptrace.o
obj-y += syscalls.o
obj-y += tty.o
obj-y += binfmt_elf_subleq.o

always-$(KBUILD_BUILTIN) := vmlinux.lds
